### ISSUE TITLE
Where is mixin?

### ISSUE THREAD

**Issue by guzmaniglesias** [inuitcss/trumps.clearfix#11]
I was surprised that there isn't (yet) a clearfix mixin on this project.
I don't disagree totally about the idea to use `@extend %clearfix;` as much as necessary but since I read the new @csswizardry article http://csswizardry.com/2016/02/mixins-better-for-performance I think that my surprise has sense. May the clearfix case worth an exception?

**Comment by csshugs** [comment]
@guzmaniglesias Your surprise isn't unfounded. Your concerns were already discussed in issue #8 .

So no, `clearfix` will not be worth an exception of this rule. The idea just was not addressed yet.

Due to the duplication of this issue, maybe you can close this one?

**Comment by guzmaniglesias** [comment]
Sure.
