### ISSUE TITLE
if its a trump?

### ISSUE THREAD

**Issue by lifeiscontent** [inuitcss/trumps.clearfix#6]
Shouldn't it have `!important` on the properties? :wink:

**Comment by sotayamashita** [comment]
I think it should not have `!important` just because it is on `trump` but I would like to why it is on here.

**Comment by sotayamashita** [comment]
I am sorry. I misunderstood about trump

**Comment by nenadjelovac** [comment]
@lifeiscontent actually, it should have that :)
