### ISSUE TITLE
Update : add namespace, remove silent classes, tools

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/trumps.clearfix#8]
I think we should consider an update.

`_tools.clearfix.scss` (or `_tools.mixin.scss`) : create a mixin to avoid silent classe :
``` 
///*------------------------------------*\
//    #CLEARFIX
//\*------------------------------------*/

@mixin inuit-clearfix() {
    &:after {
        content: "";
        display: table;
        clear: both;
    }
}
```

`_trumps.clearfix`: add utility namespace and remove silent classe : 
```
/*------------------------------------*\
    #CLEARFIX
\*------------------------------------*/

/**
 * Micro clearfix, as per: css-101.org/articles/clearfix/latest-new-clearfix-so-far.php
 * Extend the clearfix class with Sass to avoid the `.clearfix` class appearing
 * over and over in your markup.
 */
.u-clearfix {
    @include inuit-clearfix();
}
```

*`_objects.box.scss` : update clearfix `@extend %clearfix;` > `@include inuit-clearfix;`*

What is your opinion @csswizardry @nenadjelovac @anselmh @csshugs ?

**Comment by csshugs** [comment]
I would like to see dropping all the silent classes in the framework and I think this is a very clean approach in this case to not need to use `@extend %clearfix;`.

**Comment by anselmh** [comment]
@florianbouvot What’s the reason/intention for replacing the working silend-class extend with a mixin?
@csshugs what makes you thing that and what’s the reason? 
I’d like to collect information on why you ask for this because inuit highly relies on silent classes atm.

**Comment by nenadjelovac** [comment]
@anselmh the reason is probably Harry's brainstorming from [here](https://github.com/inuitcss/CONTRIBUTING/issues/18).

**Comment by csshugs** [comment]
@anselmh 
> @anselmh the reason is probably Harry's brainstorming from here.

Exact. I share Harry's opinion to avoid encouraging the usage of `@extend` at all in the framework. Extending makes debugging horrible and potentially breaks the well structured source order of inuitcss.

**Comment by nenadjelovac** [comment]
@florianbouvot I think this raises more questions for other inuitcss modules (and I am not sure about the answer ATM). Check [this comment](https://github.com/inuitcss/CONTRIBUTING/issues/18#issuecomment-98609413) for more info.

**Comment by florianbouvot** [comment]
@nenadjelovac you're right, my intention follows Harry's thinking [Make inuitcss a little more opinionated?](https://github.com/inuitcss/CONTRIBUTING/issues/18#issuecomment-98609413).

@anselmh my goal isn't to replace every silent-class with mixin. Clearfix mixin is necessary for box object that why I propose to work with.

**Comment by anselmh** [comment]
Closing as this won’t be done in the current version but handled in the upcoming new major version.
